// GraphQL schema types and operations
// This will be generated by AWS AppSync

export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  company?: string;
  position?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  userId: string;
}

export interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  company?: string;
  status: LeadStatus;
  source?: string;
  value?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  userId: string;
}

export interface Activity {
  id: string;
  type: ActivityType;
  title: string;
  description?: string;
  dueDate?: string;
  completed: boolean;
  contactId?: string;
  leadId?: string;
  createdAt: string;
  updatedAt: string;
  userId: string;
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  PROPOSAL = 'PROPOSAL',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED_WON = 'CLOSED_WON',
  CLOSED_LOST = 'CLOSED_LOST'
}

export enum ActivityType {
  CALL = 'CALL',
  EMAIL = 'EMAIL',
  MEETING = 'MEETING',
  TASK = 'TASK',
  NOTE = 'NOTE'
}